spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
       hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/cadastro?createDatabaseIfNotExist=true
    username: iuri
    password: 123456

server:
  port: 8080
